rmi.host=localhost
rmi.port=1099
rmi.name=RestaurantService
station.info.url=https://api.cyclocity.fr/contracts/nancy/gbfs/v2/station_information.json
station.status.url=https://api.cyclocity.fr/contracts/nancy/gbfs/v2/station_status.json
incidents.url=https://carto.g-ny.eu/data/cifs/cifs_waze_v2.json
port=8000
